# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
        ('users', '0003_auto_20170715_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_blog',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog'),
        ),
    ]
