# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='num',
            field=models.TextField(default='0'),
        ),
    ]
