# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20170716_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='num',
            field=models.IntegerField(null=True),
        ),
    ]
