# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20170716_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='isDefault',
            field=models.BooleanField(default=True),
        ),
    ]
