# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_comment_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='num',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
